In [19]:
import requests
import pandas as pd


URL = "https://apeboard.finance/dashboard/0x6C7875d66b5c9D9cfe910fa211CF4D409780867F"
page = requests.get(URL)

In [20]:

import json
URL1 = "https://api.coinstats.app/public/v1/coins?skip=0&limit=100&currency=USD"
page1 = requests.get(URL1)

#list(page.text.items())
jsonpage = json.loads(page1.text)

In [21]:

df = pd.read_csv(r'/Users/ben/Desktop/Export Wallets 2021-12-07-235820.csv')
print (df)

                                 wallet_address     chain  \
0    0x6C7875d66b5c9D9cfe910fa211CF4D409780867F  ETHEREUM
1    0x6C7875d66b5c9D9cfe910fa211CF4D409780867F  ETHEREUM
2    0x6C7875d66b5c9D9cfe910fa211CF4D409780867F  ETHEREUM
3    0x6C7875d66b5c9D9cfe910fa211CF4D409780867F  ETHEREUM
4  Eo6Wqq4HmtZbWAHyo67tuDLkstfcBVPRfQXBwGZZzo5C    SOLANA
5  Eo6Wqq4HmtZbWAHyo67tuDLkstfcBVPRfQXBwGZZzo5C    SOLANA
6    0x6C7875d66b5c9D9cfe910fa211CF4D409780867F   POLYGON

                                  token_address symbol       balance  \
0    0x249e38ea4102d0cf8264d3701f1a0e39c4f2dc3b    UFO  7.300550e+06
1    0x383518188c0c6d7730d91b2c03a03c837814a899    OHM  1.394648e-01
2    0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee    ETH  1.633406e-02
3    0xae7ab96520de3a18e5e111b5eaab095312d7fe84  STETH  1.000000e-18
4  EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v   USDC  1.057884e+01
5              11111111111111111111111111111111    SOL  2.413929e-02
6    0x0000000000000000000000000000000000001010  MATIC  6.275443e+00

         price         value
0     0.000031  2.237173e+02
1   533.470000  7.440026e+01
2  4309.160000  7.038609e+01
3  4270.190000  4.270190e-15
4     0.997042  1.054755e+01
5   187.110000  4.516703e+00
6     2.250000  1.411975e+01

In [22]:
df

,wallet_address,chain,token_address,symbol,balance,price,value
0,0x6C7875d66b5c9D9cfe910fa211CF4D409780867F,ETHEREUM,0x249e38ea4102d0cf8264d3701f1a0e39c4f2dc3b,UFO,7.300550e+06,0.000031,2.237173e+02
1,0x6C7875d66b5c9D9cfe910fa211CF4D409780867F,ETHEREUM,0x383518188c0c6d7730d91b2c03a03c837814a899,OHM,1.394648e-01,533.470000,7.440026e+01
2,0x6C7875d66b5c9D9cfe910fa211CF4D409780867F,ETHEREUM,0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee,ETH,1.633406e-02,4309.160000,7.038609e+01
3,0x6C7875d66b5c9D9cfe910fa211CF4D409780867F,ETHEREUM,0xae7ab96520de3a18e5e111b5eaab095312d7fe84,STETH,1.000000e-18,4270.190000,4.270190e-15
4,Eo6Wqq4HmtZbWAHyo67tuDLkstfcBVPRfQXBwGZZzo5C,SOLANA,EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v,USDC,1.057884e+01,0.997042,1.054755e+01
5,Eo6Wqq4HmtZbWAHyo67tuDLkstfcBVPRfQXBwGZZzo5C,SOLANA,11111111111111111111111111111111,SOL,2.413929e-02,187.110000,4.516703e+00
6,0x6C7875d66b5c9D9cfe910fa211CF4D409780867F,POLYGON,0x0000000000000000000000000000000000001010,MATIC,6.275443e+00,2.250000,1.411975e+01

In [23]:
df["symbol"][1]

'OHM'

In [24]:
import json

In [25]:
volume_list= []
price_list = []
name_list = []
symbol_list = []

priceChange1w_list = []


for i in range(len(jsonpage['coins'])):
    if jsonpage['coins'][i]['symbol'] in str(df['symbol']):
        volume_list.append(jsonpage['coins'][i]["volume"])
        price_list.append(jsonpage['coins'][i]["price"])
        name_list.append(jsonpage['coins'][i]['name']) 
        priceChange1w_list.append(jsonpage['coins'][i]["priceChange1w"])
        symbol_list.append(jsonpage['coins'][i]["symbol"])

In [26]:
import matplotlib.pyplot as plt
import numpy as np

In [27]:
d = {
    "volume": volume_list,
    "price": price_list,
    "name": name_list,
    "price_change_1w": priceChange1w_list,
    "symbol": symbol_list
}

In [28]:
pdf = pd.DataFrame(d)

In [29]:
pdf

         volume        price               name  price_change_1w symbol
0  3.732917e+10  4311.487657           Ethereum            -7.91    ETH
1  2.957853e+09   188.625291             Solana           -15.90    SOL
2  2.396695e+09     0.999024           USD Coin             0.13   USDC
3  5.967874e+09     2.396435            Polygon            18.57  MATIC
4  1.388303e+07  4270.290000  Lido Staked Ether            -7.10  STETH
5  7.369961e+07   495.570000            Olympus           -39.09    OHM

In [30]:
df.sort_values(by=['symbol'])

,wallet_address,chain,token_address,symbol,balance,price,value
2,0x6C7875d66b5c9D9cfe910fa211CF4D409780867F,ETHEREUM,0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee,ETH,1.633406e-02,4309.160000,7.038609e+01
6,0x6C7875d66b5c9D9cfe910fa211CF4D409780867F,POLYGON,0x0000000000000000000000000000000000001010,MATIC,6.275443e+00,2.250000,1.411975e+01
1,0x6C7875d66b5c9D9cfe910fa211CF4D409780867F,ETHEREUM,0x383518188c0c6d7730d91b2c03a03c837814a899,OHM,1.394648e-01,533.470000,7.440026e+01
5,Eo6Wqq4HmtZbWAHyo67tuDLkstfcBVPRfQXBwGZZzo5C,SOLANA,11111111111111111111111111111111,SOL,2.413929e-02,187.110000,4.516703e+00
3,0x6C7875d66b5c9D9cfe910fa211CF4D409780867F,ETHEREUM,0xae7ab96520de3a18e5e111b5eaab095312d7fe84,STETH,1.000000e-18,4270.190000,4.270190e-15
0,0x6C7875d66b5c9D9cfe910fa211CF4D409780867F,ETHEREUM,0x249e38ea4102d0cf8264d3701f1a0e39c4f2dc3b,UFO,7.300550e+06,0.000031,2.237173e+02
4,Eo6Wqq4HmtZbWAHyo67tuDLkstfcBVPRfQXBwGZZzo5C,SOLANA,EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v,USDC,1.057884e+01,0.997042,1.054755e+01

In [31]:
sortedpdf = pdf.set_index('symbol')
sorteddf = df.drop(0).set_index('symbol')

In [32]:
sortedpdf

              volume        price               name  price_change_1w
symbol
ETH     3.732917e+10  4311.487657           Ethereum            -7.91
SOL     2.957853e+09   188.625291             Solana           -15.90
USDC    2.396695e+09     0.999024           USD Coin             0.13
MATIC   5.967874e+09     2.396435            Polygon            18.57
STETH   1.388303e+07  4270.290000  Lido Staked Ether            -7.10
OHM     7.369961e+07   495.570000            Olympus           -39.09

In [33]:
sorteddf

,wallet_address,chain,token_address,balance,price,value
symbol,,,,,,
OHM,0x6C7875d66b5c9D9cfe910fa211CF4D409780867F,ETHEREUM,0x383518188c0c6d7730d91b2c03a03c837814a899,1.394648e-01,533.470000,7.440026e+01
ETH,0x6C7875d66b5c9D9cfe910fa211CF4D409780867F,ETHEREUM,0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee,1.633406e-02,4309.160000,7.038609e+01
STETH,0x6C7875d66b5c9D9cfe910fa211CF4D409780867F,ETHEREUM,0xae7ab96520de3a18e5e111b5eaab095312d7fe84,1.000000e-18,4270.190000,4.270190e-15
USDC,Eo6Wqq4HmtZbWAHyo67tuDLkstfcBVPRfQXBwGZZzo5C,SOLANA,EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v,1.057884e+01,0.997042,1.054755e+01
SOL,Eo6Wqq4HmtZbWAHyo67tuDLkstfcBVPRfQXBwGZZzo5C,SOLANA,11111111111111111111111111111111,2.413929e-02,187.110000,4.516703e+00
MATIC,0x6C7875d66b5c9D9cfe910fa211CF4D409780867F,POLYGON,0x0000000000000000000000000000000000001010,6.275443e+00,2.250000,1.411975e+01

getApeBoardPriceMomentum(path) takes the local path to your exported ApeBoard data, and returns a weighted index on your portfolio's peformance over the past week based on the amount you own of each asset and it's performance over the past week. Data is taken from coinlist's api.

In [34]:

def getApeBoardPricemomentum(path):
    df = pd.read_csv(path)
    URL1 = "https://api.coinstats.app/public/v1/coins?skip=0&limit=100&currency=USD"
    page1 = requests.get(URL1)
    jsonpage = json.loads(page1.text)
    
    volume_list= []
    price_list = []
    name_list = []
    symbol_list = []
    priceChange1w_list = []
    
    for i in range(len(jsonpage['coins'])):
        if jsonpage['coins'][i]['symbol'] in str(df['symbol']):
            volume_list.append(jsonpage['coins'][i]["volume"])
            price_list.append(jsonpage['coins'][i]["price"])
            name_list.append(jsonpage['coins'][i]['name']) 
            priceChange1w_list.append(jsonpage['coins'][i]["priceChange1w"])
            symbol_list.append(jsonpage['coins'][i]["symbol"])
    d = {
    "volume": volume_list,
    "price": price_list,
    "name": name_list,
    "price_change_1w": priceChange1w_list,
    "symbol": symbol_list}
    pdf = pd.DataFrame(d)
    sortedpdf = pdf
    sorteddf = df.drop(0)
    
    #calculate the total value of portfolio
    # total portfolio price change = pc1*(val1/total) + ....
    total = sorteddf['balance'].sum()
    price_movement_1w = 0
    
    for i in symbol_list:
        dfloc = sorteddf.loc[sorteddf['symbol'] == i]
        pdfloc = sortedpdf.loc[sortedpdf['symbol'] == i]
        bal = dfloc['balance']
        chng = pdfloc['price_change_1w']
        price_movement_1w = price_movement_1w + (chng.item() * (bal.item()/total))
        
    return "Your Apeboard portfolio's weighted price movement index for the past week is " + str(price_movement_1w) + "%"

In [35]:
getApeBoardPricemomentum("/Users/ben/Desktop/Export Wallets 2021-12-07-235820.csv")

"Your Apeboard portfolio's weighted price movement index for the past week is 6.5718017059092295%"